{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "BASE_URL = 'https://embracedata.inpe.br/'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 116,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "def find_files(url):\n",
    "    resp = requests.get(url)\n",
    "    soup = BeautifulSoup(resp.text, \"html.parser\")\n",
    "    return [a['href'] for a in soup.find_all('a', href=True) if not ';' in a['href'] and not a['href'].endswith('/')]\n",
    "\n",
    "\n",
    "def build_url(root_url):\n",
    "    urls = []\n",
    "    res = requests.get(root_url)\n",
    "    soup = BeautifulSoup(res.text, \"html.parser\")\n",
    "    relative_paths = [a['href'] for a in soup.find_all('a', href=True) if len(a['href']) > 1 and a['href'][-1] == '/']\n",
    "    \n",
    "    if relative_paths:\n",
    "        for path in relative_paths:\n",
    "            if path not in root_url:\n",
    "                urls.append(root_url + path)\n",
    "    return urls"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 117,
   "metadata": {},
   "outputs": [],
   "source": [
    "magnetometer_url = [build_url(i) for i in build_url('https://embracedata.inpe.br/magnetometer/')]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 120,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[['https://embracedata.inpe.br/magnetometer/ALF/2014/',\n",
       "  'https://embracedata.inpe.br/magnetometer/ALF/2015/',\n",
       "  'https://embracedata.inpe.br/magnetometer/ALF/2016/',\n",
       "  'https://embracedata.inpe.br/magnetometer/ALF/2017/',\n",
       "  'https://embracedata.inpe.br/magnetometer/ALF/2018/',\n",
       "  'https://embracedata.inpe.br/magnetometer/ALF/2019/'],\n",
       " ['https://embracedata.inpe.br/magnetometer/ARA/2016/',\n",
       "  'https://embracedata.inpe.br/magnetometer/ARA/2017/',\n",
       "  'https://embracedata.inpe.br/magnetometer/ARA/2018/',\n",
       "  'https://embracedata.inpe.br/magnetometer/ARA/2019/',\n",
       "  'https://embracedata.inpe.br/magnetometer/ARA/2020/',\n",
       "  'https://embracedata.inpe.br/magnetometer/ARA/2021/',\n",
       "  'https://embracedata.inpe.br/magnetometer/ARA/2022/',\n",
       "  'https://embracedata.inpe.br/magnetometer/ARA/2023/'],\n",
       " ['https://embracedata.inpe.br/magnetometer/CBA/2014/',\n",
       "  'https://embracedata.inpe.br/magnetometer/CBA/2015/',\n",
       "  'https://embracedata.inpe.br/magnetometer/CBA/2016/',\n",
       "  'https://embracedata.inpe.br/magnetometer/CBA/2017/',\n",
       "  'https://embracedata.inpe.br/magnetometer/CBA/2018/',\n",
       "  'https://embracedata.inpe.br/magnetometer/CBA/2019/',\n",
       "  'https://embracedata.inpe.br/magnetometer/CBA/2020/',\n",
       "  'https://embracedata.inpe.br/magnetometer/CBA/2021/',\n",
       "  'https://embracedata.inpe.br/magnetometer/CBA/2022/',\n",
       "  'https://embracedata.inpe.br/magnetometer/CBA/2023/'],\n",
       " ['https://embracedata.inpe.br/magnetometer/CHI/2019/',\n",
       "  'https://embracedata.inpe.br/magnetometer/CHI/2020/',\n",
       "  'https://embracedata.inpe.br/magnetometer/CHI/2021/',\n",
       "  'https://embracedata.inpe.br/magnetometer/CHI/2022/',\n",
       "  'https://embracedata.inpe.br/magnetometer/CHI/2023/'],\n",
       " ['https://embracedata.inpe.br/magnetometer/CXP/2012/',\n",
       "  'https://embracedata.inpe.br/magnetometer/CXP/2013/',\n",
       "  'https://embracedata.inpe.br/magnetometer/CXP/2014/',\n",
       "  'https://embracedata.inpe.br/magnetometer/CXP/2015/',\n",
       "  'https://embracedata.inpe.br/magnetometer/CXP/2016/',\n",
       "  'https://embracedata.inpe.br/magnetometer/CXP/2017/',\n",
       "  'https://embracedata.inpe.br/magnetometer/CXP/2018/',\n",
       "  'https://embracedata.inpe.br/magnetometer/CXP/2019/',\n",
       "  'https://embracedata.inpe.br/magnetometer/CXP/2020/',\n",
       "  'https://embracedata.inpe.br/magnetometer/CXP/2021/',\n",
       "  'https://embracedata.inpe.br/magnetometer/CXP/2022/',\n",
       "  'https://embracedata.inpe.br/magnetometer/CXP/2023/'],\n",
       " ['https://embracedata.inpe.br/magnetometer/EUS/2012/',\n",
       "  'https://embracedata.inpe.br/magnetometer/EUS/2013/',\n",
       "  'https://embracedata.inpe.br/magnetometer/EUS/2014/',\n",
       "  'https://embracedata.inpe.br/magnetometer/EUS/2015/',\n",
       "  'https://embracedata.inpe.br/magnetometer/EUS/2016/',\n",
       "  'https://embracedata.inpe.br/magnetometer/EUS/2017/',\n",
       "  'https://embracedata.inpe.br/magnetometer/EUS/2018/',\n",
       "  'https://embracedata.inpe.br/magnetometer/EUS/2019/',\n",
       "  'https://embracedata.inpe.br/magnetometer/EUS/2020/',\n",
       "  'https://embracedata.inpe.br/magnetometer/EUS/2021/',\n",
       "  'https://embracedata.inpe.br/magnetometer/EUS/2022/',\n",
       "  'https://embracedata.inpe.br/magnetometer/EUS/2023/'],\n",
       " ['https://embracedata.inpe.br/magnetometer/JAT/2013/',\n",
       "  'https://embracedata.inpe.br/magnetometer/JAT/2014/',\n",
       "  'https://embracedata.inpe.br/magnetometer/JAT/2015/',\n",
       "  'https://embracedata.inpe.br/magnetometer/JAT/2016/',\n",
       "  'https://embracedata.inpe.br/magnetometer/JAT/2017/',\n",
       "  'https://embracedata.inpe.br/magnetometer/JAT/2018/',\n",
       "  'https://embracedata.inpe.br/magnetometer/JAT/2019/',\n",
       "  'https://embracedata.inpe.br/magnetometer/JAT/2020/',\n",
       "  'https://embracedata.inpe.br/magnetometer/JAT/2021/',\n",
       "  'https://embracedata.inpe.br/magnetometer/JAT/2022/',\n",
       "  'https://embracedata.inpe.br/magnetometer/JAT/2023/'],\n",
       " ['https://embracedata.inpe.br/magnetometer/MAN/2016/',\n",
       "  'https://embracedata.inpe.br/magnetometer/MAN/2017/'],\n",
       " ['https://embracedata.inpe.br/magnetometer/MED/2018/',\n",
       "  'https://embracedata.inpe.br/magnetometer/MED/2019/',\n",
       "  'https://embracedata.inpe.br/magnetometer/MED/2020/',\n",
       "  'https://embracedata.inpe.br/magnetometer/MED/2021/',\n",
       "  'https://embracedata.inpe.br/magnetometer/MED/2022/',\n",
       "  'https://embracedata.inpe.br/magnetometer/MED/2023/'],\n",
       " ['https://embracedata.inpe.br/magnetometer/PAL/2019/',\n",
       "  'https://embracedata.inpe.br/magnetometer/PAL/2020/',\n",
       "  'https://embracedata.inpe.br/magnetometer/PAL/2021/',\n",
       "  'https://embracedata.inpe.br/magnetometer/PAL/2022/'],\n",
       " ['https://embracedata.inpe.br/magnetometer/PVE/2019/',\n",
       "  'https://embracedata.inpe.br/magnetometer/PVE/2020/',\n",
       "  'https://embracedata.inpe.br/magnetometer/PVE/2021/',\n",
       "  'https://embracedata.inpe.br/magnetometer/PVE/2022/',\n",
       "  'https://embracedata.inpe.br/magnetometer/PVE/2023/'],\n",
       " ['https://embracedata.inpe.br/magnetometer/RGA/2012/',\n",
       "  'https://embracedata.inpe.br/magnetometer/RGA/2013/',\n",
       "  'https://embracedata.inpe.br/magnetometer/RGA/2014/',\n",
       "  'https://embracedata.inpe.br/magnetometer/RGA/2015/',\n",
       "  'https://embracedata.inpe.br/magnetometer/RGA/2016/',\n",
       "  'https://embracedata.inpe.br/magnetometer/RGA/2017/',\n",
       "  'https://embracedata.inpe.br/magnetometer/RGA/2018/',\n",
       "  'https://embracedata.inpe.br/magnetometer/RGA/2019/',\n",
       "  'https://embracedata.inpe.br/magnetometer/RGA/2020/',\n",
       "  'https://embracedata.inpe.br/magnetometer/RGA/2021/',\n",
       "  'https://embracedata.inpe.br/magnetometer/RGA/2022/',\n",
       "  'https://embracedata.inpe.br/magnetometer/RGA/2023/'],\n",
       " ['https://embracedata.inpe.br/magnetometer/SJC/2013/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SJC/2014/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SJC/2015/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SJC/2016/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SJC/2017/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SJC/2018/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SJC/2019/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SJC/2020/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SJC/2021/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SJC/2022/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SJC/2023/'],\n",
       " ['https://embracedata.inpe.br/magnetometer/SLZ/2012/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SLZ/2013/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SLZ/2014/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SLZ/2015/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SLZ/2016/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SLZ/2017/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SLZ/2018/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SLZ/2019/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SLZ/2020/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SLZ/2021/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SLZ/2022/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SLZ/2023/'],\n",
       " ['https://embracedata.inpe.br/magnetometer/SMS/2013/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SMS/2014/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SMS/2015/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SMS/2016/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SMS/2017/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SMS/2018/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SMS/2019/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SMS/2020/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SMS/2021/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SMS/2022/',\n",
       "  'https://embracedata.inpe.br/magnetometer/SMS/2023/'],\n",
       " ['https://embracedata.inpe.br/magnetometer/STM/2022/',\n",
       "  'https://embracedata.inpe.br/magnetometer/STM/2023/'],\n",
       " ['https://embracedata.inpe.br/magnetometer/TCM/2016/',\n",
       "  'https://embracedata.inpe.br/magnetometer/TCM/2017/',\n",
       "  'https://embracedata.inpe.br/magnetometer/TCM/2018/',\n",
       "  'https://embracedata.inpe.br/magnetometer/TCM/2019/',\n",
       "  'https://embracedata.inpe.br/magnetometer/TCM/2020/',\n",
       "  'https://embracedata.inpe.br/magnetometer/TCM/2021/',\n",
       "  'https://embracedata.inpe.br/magnetometer/TCM/2022/',\n",
       "  'https://embracedata.inpe.br/magnetometer/TCM/2023/'],\n",
       " ['https://embracedata.inpe.br/magnetometer/VSS/2015/',\n",
       "  'https://embracedata.inpe.br/magnetometer/VSS/2016/',\n",
       "  'https://embracedata.inpe.br/magnetometer/VSS/2017/',\n",
       "  'https://embracedata.inpe.br/magnetometer/VSS/2018/',\n",
       "  'https://embracedata.inpe.br/magnetometer/VSS/2019/',\n",
       "  'https://embracedata.inpe.br/magnetometer/VSS/2020/',\n",
       "  'https://embracedata.inpe.br/magnetometer/VSS/2021/',\n",
       "  'https://embracedata.inpe.br/magnetometer/VSS/2022/',\n",
       "  'https://embracedata.inpe.br/magnetometer/VSS/2023/']]"
      ]
     },
     "execution_count": 120,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "magnetometer_url"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 118,
   "metadata": {},
   "outputs": [],
   "source": [
    "def write_file(data: str, file_name: str):\n",
    "    os.makedirs(os.path.dirname(file_name), exist_ok=True)\n",
    "    with open(file_name, 'w') as f:\n",
    "        f.write(data)\n",
    "\n",
    "def download_file(url: str):\n",
    "    data = requests.get(url).text\n",
    "    write_file(data=data, file_name=url.replace(BASE_URL, ''))\n",
    "\n",
    "\n",
    "def download_all_files(urls: list):\n",
    "    for url in urls:\n",
    "        download_file(url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 119,
   "metadata": {},
   "outputs": [
    {
     "ename": "ConnectionError",
     "evalue": "('Connection aborted.', OSError(107, 'Transport endpoint is not connected'))",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mOSError\u001b[0m                                   Traceback (most recent call last)",
      "File \u001b[0;32m~/tcc/venv/lib/python3.10/site-packages/urllib3/connectionpool.py:703\u001b[0m, in \u001b[0;36mHTTPConnectionPool.urlopen\u001b[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[1;32m    702\u001b[0m \u001b[39m# Make the request on the httplib connection object.\u001b[39;00m\n\u001b[0;32m--> 703\u001b[0m httplib_response \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_make_request(\n\u001b[1;32m    704\u001b[0m     conn,\n\u001b[1;32m    705\u001b[0m     method,\n\u001b[1;32m    706\u001b[0m     url,\n\u001b[1;32m    707\u001b[0m     timeout\u001b[39m=\u001b[39;49mtimeout_obj,\n\u001b[1;32m    708\u001b[0m     body\u001b[39m=\u001b[39;49mbody,\n\u001b[1;32m    709\u001b[0m     headers\u001b[39m=\u001b[39;49mheaders,\n\u001b[1;32m    710\u001b[0m     chunked\u001b[39m=\u001b[39;49mchunked,\n\u001b[1;32m    711\u001b[0m )\n\u001b[1;32m    713\u001b[0m \u001b[39m# If we're going to release the connection in ``finally:``, then\u001b[39;00m\n\u001b[1;32m    714\u001b[0m \u001b[39m# the response doesn't need to know about the connection. Otherwise\u001b[39;00m\n\u001b[1;32m    715\u001b[0m \u001b[39m# it will also try to release it and we'll have a double-release\u001b[39;00m\n\u001b[1;32m    716\u001b[0m \u001b[39m# mess.\u001b[39;00m\n",
      "File \u001b[0;32m~/tcc/venv/lib/python3.10/site-packages/urllib3/connectionpool.py:386\u001b[0m, in \u001b[0;36mHTTPConnectionPool._make_request\u001b[0;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)\u001b[0m\n\u001b[1;32m    385\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> 386\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_validate_conn(conn)\n\u001b[1;32m    387\u001b[0m \u001b[39mexcept\u001b[39;00m (SocketTimeout, BaseSSLError) \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m    388\u001b[0m     \u001b[39m# Py2 raises this as a BaseSSLError, Py3 raises it as socket timeout.\u001b[39;00m\n",
      "File \u001b[0;32m~/tcc/venv/lib/python3.10/site-packages/urllib3/connectionpool.py:1042\u001b[0m, in \u001b[0;36mHTTPSConnectionPool._validate_conn\u001b[0;34m(self, conn)\u001b[0m\n\u001b[1;32m   1041\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mgetattr\u001b[39m(conn, \u001b[39m\"\u001b[39m\u001b[39msock\u001b[39m\u001b[39m\"\u001b[39m, \u001b[39mNone\u001b[39;00m):  \u001b[39m# AppEngine might not have  `.sock`\u001b[39;00m\n\u001b[0;32m-> 1042\u001b[0m     conn\u001b[39m.\u001b[39;49mconnect()\n\u001b[1;32m   1044\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m conn\u001b[39m.\u001b[39mis_verified:\n",
      "File \u001b[0;32m~/tcc/venv/lib/python3.10/site-packages/urllib3/connection.py:461\u001b[0m, in \u001b[0;36mHTTPSConnection.connect\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    453\u001b[0m \u001b[39melif\u001b[39;00m (\n\u001b[1;32m    454\u001b[0m     context\u001b[39m.\u001b[39mverify_mode \u001b[39m!=\u001b[39m ssl\u001b[39m.\u001b[39mCERT_NONE\n\u001b[1;32m    455\u001b[0m     \u001b[39mand\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mgetattr\u001b[39m(context, \u001b[39m\"\u001b[39m\u001b[39mcheck_hostname\u001b[39m\u001b[39m\"\u001b[39m, \u001b[39mFalse\u001b[39;00m)\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    459\u001b[0m     \u001b[39m# the TLS library, this cannot always be done. So we check whether\u001b[39;00m\n\u001b[1;32m    460\u001b[0m     \u001b[39m# the TLS Library still thinks it's matching hostnames.\u001b[39;00m\n\u001b[0;32m--> 461\u001b[0m     cert \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49msock\u001b[39m.\u001b[39;49mgetpeercert()\n\u001b[1;32m    462\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m cert\u001b[39m.\u001b[39mget(\u001b[39m\"\u001b[39m\u001b[39msubjectAltName\u001b[39m\u001b[39m\"\u001b[39m, ()):\n",
      "File \u001b[0;32m/usr/lib/python3.10/ssl.py:1154\u001b[0m, in \u001b[0;36mSSLSocket.getpeercert\u001b[0;34m(self, binary_form)\u001b[0m\n\u001b[1;32m   1153\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_checkClosed()\n\u001b[0;32m-> 1154\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_check_connected()\n\u001b[1;32m   1155\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_sslobj\u001b[39m.\u001b[39mgetpeercert(binary_form)\n",
      "File \u001b[0;32m/usr/lib/python3.10/ssl.py:1119\u001b[0m, in \u001b[0;36mSSLSocket._check_connected\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1114\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_connected:\n\u001b[1;32m   1115\u001b[0m     \u001b[39m# getpeername() will raise ENOTCONN if the socket is really\u001b[39;00m\n\u001b[1;32m   1116\u001b[0m     \u001b[39m# not connected; note that we can be connected even without\u001b[39;00m\n\u001b[1;32m   1117\u001b[0m     \u001b[39m# _connected being set, e.g. if connect() first returned\u001b[39;00m\n\u001b[1;32m   1118\u001b[0m     \u001b[39m# EAGAIN.\u001b[39;00m\n\u001b[0;32m-> 1119\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mgetpeername()\n",
      "\u001b[0;31mOSError\u001b[0m: [Errno 107] Transport endpoint is not connected",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mProtocolError\u001b[0m                             Traceback (most recent call last)",
      "File \u001b[0;32m~/tcc/venv/lib/python3.10/site-packages/requests/adapters.py:489\u001b[0m, in \u001b[0;36mHTTPAdapter.send\u001b[0;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[1;32m    488\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m chunked:\n\u001b[0;32m--> 489\u001b[0m     resp \u001b[39m=\u001b[39m conn\u001b[39m.\u001b[39;49murlopen(\n\u001b[1;32m    490\u001b[0m         method\u001b[39m=\u001b[39;49mrequest\u001b[39m.\u001b[39;49mmethod,\n\u001b[1;32m    491\u001b[0m         url\u001b[39m=\u001b[39;49murl,\n\u001b[1;32m    492\u001b[0m         body\u001b[39m=\u001b[39;49mrequest\u001b[39m.\u001b[39;49mbody,\n\u001b[1;32m    493\u001b[0m         headers\u001b[39m=\u001b[39;49mrequest\u001b[39m.\u001b[39;49mheaders,\n\u001b[1;32m    494\u001b[0m         redirect\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m,\n\u001b[1;32m    495\u001b[0m         assert_same_host\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m,\n\u001b[1;32m    496\u001b[0m         preload_content\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m,\n\u001b[1;32m    497\u001b[0m         decode_content\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m,\n\u001b[1;32m    498\u001b[0m         retries\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mmax_retries,\n\u001b[1;32m    499\u001b[0m         timeout\u001b[39m=\u001b[39;49mtimeout,\n\u001b[1;32m    500\u001b[0m     )\n\u001b[1;32m    502\u001b[0m \u001b[39m# Send the request.\u001b[39;00m\n\u001b[1;32m    503\u001b[0m \u001b[39melse\u001b[39;00m:\n",
      "File \u001b[0;32m~/tcc/venv/lib/python3.10/site-packages/urllib3/connectionpool.py:787\u001b[0m, in \u001b[0;36mHTTPConnectionPool.urlopen\u001b[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[1;32m    785\u001b[0m     e \u001b[39m=\u001b[39m ProtocolError(\u001b[39m\"\u001b[39m\u001b[39mConnection aborted.\u001b[39m\u001b[39m\"\u001b[39m, e)\n\u001b[0;32m--> 787\u001b[0m retries \u001b[39m=\u001b[39m retries\u001b[39m.\u001b[39;49mincrement(\n\u001b[1;32m    788\u001b[0m     method, url, error\u001b[39m=\u001b[39;49me, _pool\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m, _stacktrace\u001b[39m=\u001b[39;49msys\u001b[39m.\u001b[39;49mexc_info()[\u001b[39m2\u001b[39;49m]\n\u001b[1;32m    789\u001b[0m )\n\u001b[1;32m    790\u001b[0m retries\u001b[39m.\u001b[39msleep()\n",
      "File \u001b[0;32m~/tcc/venv/lib/python3.10/site-packages/urllib3/util/retry.py:550\u001b[0m, in \u001b[0;36mRetry.increment\u001b[0;34m(self, method, url, response, error, _pool, _stacktrace)\u001b[0m\n\u001b[1;32m    549\u001b[0m \u001b[39mif\u001b[39;00m read \u001b[39mis\u001b[39;00m \u001b[39mFalse\u001b[39;00m \u001b[39mor\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_is_method_retryable(method):\n\u001b[0;32m--> 550\u001b[0m     \u001b[39mraise\u001b[39;00m six\u001b[39m.\u001b[39;49mreraise(\u001b[39mtype\u001b[39;49m(error), error, _stacktrace)\n\u001b[1;32m    551\u001b[0m \u001b[39melif\u001b[39;00m read \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n",
      "File \u001b[0;32m~/tcc/venv/lib/python3.10/site-packages/urllib3/packages/six.py:769\u001b[0m, in \u001b[0;36mreraise\u001b[0;34m(tp, value, tb)\u001b[0m\n\u001b[1;32m    768\u001b[0m \u001b[39mif\u001b[39;00m value\u001b[39m.\u001b[39m__traceback__ \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m tb:\n\u001b[0;32m--> 769\u001b[0m     \u001b[39mraise\u001b[39;00m value\u001b[39m.\u001b[39mwith_traceback(tb)\n\u001b[1;32m    770\u001b[0m \u001b[39mraise\u001b[39;00m value\n",
      "File \u001b[0;32m~/tcc/venv/lib/python3.10/site-packages/urllib3/connectionpool.py:703\u001b[0m, in \u001b[0;36mHTTPConnectionPool.urlopen\u001b[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[1;32m    702\u001b[0m \u001b[39m# Make the request on the httplib connection object.\u001b[39;00m\n\u001b[0;32m--> 703\u001b[0m httplib_response \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_make_request(\n\u001b[1;32m    704\u001b[0m     conn,\n\u001b[1;32m    705\u001b[0m     method,\n\u001b[1;32m    706\u001b[0m     url,\n\u001b[1;32m    707\u001b[0m     timeout\u001b[39m=\u001b[39;49mtimeout_obj,\n\u001b[1;32m    708\u001b[0m     body\u001b[39m=\u001b[39;49mbody,\n\u001b[1;32m    709\u001b[0m     headers\u001b[39m=\u001b[39;49mheaders,\n\u001b[1;32m    710\u001b[0m     chunked\u001b[39m=\u001b[39;49mchunked,\n\u001b[1;32m    711\u001b[0m )\n\u001b[1;32m    713\u001b[0m \u001b[39m# If we're going to release the connection in ``finally:``, then\u001b[39;00m\n\u001b[1;32m    714\u001b[0m \u001b[39m# the response doesn't need to know about the connection. Otherwise\u001b[39;00m\n\u001b[1;32m    715\u001b[0m \u001b[39m# it will also try to release it and we'll have a double-release\u001b[39;00m\n\u001b[1;32m    716\u001b[0m \u001b[39m# mess.\u001b[39;00m\n",
      "File \u001b[0;32m~/tcc/venv/lib/python3.10/site-packages/urllib3/connectionpool.py:386\u001b[0m, in \u001b[0;36mHTTPConnectionPool._make_request\u001b[0;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)\u001b[0m\n\u001b[1;32m    385\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> 386\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_validate_conn(conn)\n\u001b[1;32m    387\u001b[0m \u001b[39mexcept\u001b[39;00m (SocketTimeout, BaseSSLError) \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m    388\u001b[0m     \u001b[39m# Py2 raises this as a BaseSSLError, Py3 raises it as socket timeout.\u001b[39;00m\n",
      "File \u001b[0;32m~/tcc/venv/lib/python3.10/site-packages/urllib3/connectionpool.py:1042\u001b[0m, in \u001b[0;36mHTTPSConnectionPool._validate_conn\u001b[0;34m(self, conn)\u001b[0m\n\u001b[1;32m   1041\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mgetattr\u001b[39m(conn, \u001b[39m\"\u001b[39m\u001b[39msock\u001b[39m\u001b[39m\"\u001b[39m, \u001b[39mNone\u001b[39;00m):  \u001b[39m# AppEngine might not have  `.sock`\u001b[39;00m\n\u001b[0;32m-> 1042\u001b[0m     conn\u001b[39m.\u001b[39;49mconnect()\n\u001b[1;32m   1044\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m conn\u001b[39m.\u001b[39mis_verified:\n",
      "File \u001b[0;32m~/tcc/venv/lib/python3.10/site-packages/urllib3/connection.py:461\u001b[0m, in \u001b[0;36mHTTPSConnection.connect\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    453\u001b[0m \u001b[39melif\u001b[39;00m (\n\u001b[1;32m    454\u001b[0m     context\u001b[39m.\u001b[39mverify_mode \u001b[39m!=\u001b[39m ssl\u001b[39m.\u001b[39mCERT_NONE\n\u001b[1;32m    455\u001b[0m     \u001b[39mand\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mgetattr\u001b[39m(context, \u001b[39m\"\u001b[39m\u001b[39mcheck_hostname\u001b[39m\u001b[39m\"\u001b[39m, \u001b[39mFalse\u001b[39;00m)\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    459\u001b[0m     \u001b[39m# the TLS library, this cannot always be done. So we check whether\u001b[39;00m\n\u001b[1;32m    460\u001b[0m     \u001b[39m# the TLS Library still thinks it's matching hostnames.\u001b[39;00m\n\u001b[0;32m--> 461\u001b[0m     cert \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49msock\u001b[39m.\u001b[39;49mgetpeercert()\n\u001b[1;32m    462\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m cert\u001b[39m.\u001b[39mget(\u001b[39m\"\u001b[39m\u001b[39msubjectAltName\u001b[39m\u001b[39m\"\u001b[39m, ()):\n",
      "File \u001b[0;32m/usr/lib/python3.10/ssl.py:1154\u001b[0m, in \u001b[0;36mSSLSocket.getpeercert\u001b[0;34m(self, binary_form)\u001b[0m\n\u001b[1;32m   1153\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_checkClosed()\n\u001b[0;32m-> 1154\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_check_connected()\n\u001b[1;32m   1155\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_sslobj\u001b[39m.\u001b[39mgetpeercert(binary_form)\n",
      "File \u001b[0;32m/usr/lib/python3.10/ssl.py:1119\u001b[0m, in \u001b[0;36mSSLSocket._check_connected\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1114\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_connected:\n\u001b[1;32m   1115\u001b[0m     \u001b[39m# getpeername() will raise ENOTCONN if the socket is really\u001b[39;00m\n\u001b[1;32m   1116\u001b[0m     \u001b[39m# not connected; note that we can be connected even without\u001b[39;00m\n\u001b[1;32m   1117\u001b[0m     \u001b[39m# _connected being set, e.g. if connect() first returned\u001b[39;00m\n\u001b[1;32m   1118\u001b[0m     \u001b[39m# EAGAIN.\u001b[39;00m\n\u001b[0;32m-> 1119\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mgetpeername()\n",
      "\u001b[0;31mProtocolError\u001b[0m: ('Connection aborted.', OSError(107, 'Transport endpoint is not connected'))",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mConnectionError\u001b[0m                           Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[119], line 4\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[39mfor\u001b[39;00m year_path \u001b[39min\u001b[39;00m station_path:\n\u001b[1;32m      3\u001b[0m     url \u001b[39m=\u001b[39m [year_path \u001b[39m+\u001b[39m file_name \u001b[39mfor\u001b[39;00m file_name \u001b[39min\u001b[39;00m find_files(year_path)]\n\u001b[0;32m----> 4\u001b[0m     download_all_files(url)\n",
      "Cell \u001b[0;32mIn[118], line 13\u001b[0m, in \u001b[0;36mdownload_all_files\u001b[0;34m(urls)\u001b[0m\n\u001b[1;32m     11\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mdownload_all_files\u001b[39m(urls: \u001b[39mlist\u001b[39m):\n\u001b[1;32m     12\u001b[0m     \u001b[39mfor\u001b[39;00m url \u001b[39min\u001b[39;00m urls:\n\u001b[0;32m---> 13\u001b[0m         download_file(url)\n",
      "Cell \u001b[0;32mIn[118], line 7\u001b[0m, in \u001b[0;36mdownload_file\u001b[0;34m(url)\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mdownload_file\u001b[39m(url: \u001b[39mstr\u001b[39m):\n\u001b[0;32m----> 7\u001b[0m     data \u001b[39m=\u001b[39m requests\u001b[39m.\u001b[39;49mget(url)\u001b[39m.\u001b[39mtext\n\u001b[1;32m      8\u001b[0m     write_file(data\u001b[39m=\u001b[39mdata, file_name\u001b[39m=\u001b[39murl\u001b[39m.\u001b[39mreplace(BASE_URL, \u001b[39m'\u001b[39m\u001b[39m'\u001b[39m))\n",
      "File \u001b[0;32m~/tcc/venv/lib/python3.10/site-packages/requests/api.py:73\u001b[0m, in \u001b[0;36mget\u001b[0;34m(url, params, **kwargs)\u001b[0m\n\u001b[1;32m     62\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mget\u001b[39m(url, params\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs):\n\u001b[1;32m     63\u001b[0m \u001b[39m    \u001b[39m\u001b[39mr\u001b[39m\u001b[39m\"\"\"Sends a GET request.\u001b[39;00m\n\u001b[1;32m     64\u001b[0m \n\u001b[1;32m     65\u001b[0m \u001b[39m    :param url: URL for the new :class:`Request` object.\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     70\u001b[0m \u001b[39m    :rtype: requests.Response\u001b[39;00m\n\u001b[1;32m     71\u001b[0m \u001b[39m    \"\"\"\u001b[39;00m\n\u001b[0;32m---> 73\u001b[0m     \u001b[39mreturn\u001b[39;00m request(\u001b[39m\"\u001b[39;49m\u001b[39mget\u001b[39;49m\u001b[39m\"\u001b[39;49m, url, params\u001b[39m=\u001b[39;49mparams, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n",
      "File \u001b[0;32m~/tcc/venv/lib/python3.10/site-packages/requests/api.py:59\u001b[0m, in \u001b[0;36mrequest\u001b[0;34m(method, url, **kwargs)\u001b[0m\n\u001b[1;32m     55\u001b[0m \u001b[39m# By using the 'with' statement we are sure the session is closed, thus we\u001b[39;00m\n\u001b[1;32m     56\u001b[0m \u001b[39m# avoid leaving sockets open which can trigger a ResourceWarning in some\u001b[39;00m\n\u001b[1;32m     57\u001b[0m \u001b[39m# cases, and look like a memory leak in others.\u001b[39;00m\n\u001b[1;32m     58\u001b[0m \u001b[39mwith\u001b[39;00m sessions\u001b[39m.\u001b[39mSession() \u001b[39mas\u001b[39;00m session:\n\u001b[0;32m---> 59\u001b[0m     \u001b[39mreturn\u001b[39;00m session\u001b[39m.\u001b[39;49mrequest(method\u001b[39m=\u001b[39;49mmethod, url\u001b[39m=\u001b[39;49murl, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n",
      "File \u001b[0;32m~/tcc/venv/lib/python3.10/site-packages/requests/sessions.py:587\u001b[0m, in \u001b[0;36mSession.request\u001b[0;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)\u001b[0m\n\u001b[1;32m    582\u001b[0m send_kwargs \u001b[39m=\u001b[39m {\n\u001b[1;32m    583\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mtimeout\u001b[39m\u001b[39m\"\u001b[39m: timeout,\n\u001b[1;32m    584\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mallow_redirects\u001b[39m\u001b[39m\"\u001b[39m: allow_redirects,\n\u001b[1;32m    585\u001b[0m }\n\u001b[1;32m    586\u001b[0m send_kwargs\u001b[39m.\u001b[39mupdate(settings)\n\u001b[0;32m--> 587\u001b[0m resp \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49msend(prep, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49msend_kwargs)\n\u001b[1;32m    589\u001b[0m \u001b[39mreturn\u001b[39;00m resp\n",
      "File \u001b[0;32m~/tcc/venv/lib/python3.10/site-packages/requests/sessions.py:701\u001b[0m, in \u001b[0;36mSession.send\u001b[0;34m(self, request, **kwargs)\u001b[0m\n\u001b[1;32m    698\u001b[0m start \u001b[39m=\u001b[39m preferred_clock()\n\u001b[1;32m    700\u001b[0m \u001b[39m# Send the request\u001b[39;00m\n\u001b[0;32m--> 701\u001b[0m r \u001b[39m=\u001b[39m adapter\u001b[39m.\u001b[39;49msend(request, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n\u001b[1;32m    703\u001b[0m \u001b[39m# Total elapsed time of the request (approximately)\u001b[39;00m\n\u001b[1;32m    704\u001b[0m elapsed \u001b[39m=\u001b[39m preferred_clock() \u001b[39m-\u001b[39m start\n",
      "File \u001b[0;32m~/tcc/venv/lib/python3.10/site-packages/requests/adapters.py:547\u001b[0m, in \u001b[0;36mHTTPAdapter.send\u001b[0;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[1;32m    544\u001b[0m             \u001b[39mraise\u001b[39;00m\n\u001b[1;32m    546\u001b[0m \u001b[39mexcept\u001b[39;00m (ProtocolError, \u001b[39mOSError\u001b[39;00m) \u001b[39mas\u001b[39;00m err:\n\u001b[0;32m--> 547\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mConnectionError\u001b[39;00m(err, request\u001b[39m=\u001b[39mrequest)\n\u001b[1;32m    549\u001b[0m \u001b[39mexcept\u001b[39;00m MaxRetryError \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m    550\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39misinstance\u001b[39m(e\u001b[39m.\u001b[39mreason, ConnectTimeoutError):\n\u001b[1;32m    551\u001b[0m         \u001b[39m# TODO: Remove this in 3.0.0: see #2811\u001b[39;00m\n",
      "\u001b[0;31mConnectionError\u001b[0m: ('Connection aborted.', OSError(107, 'Transport endpoint is not connected'))"
     ]
    }
   ],
   "source": [
    "for station_path in magnetometer_url:\n",
    "    for year_path in station_path:\n",
    "        url = [year_path + file_name for file_name in find_files(year_path)]\n",
    "        download_all_files(url)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
